In [6]:
import numpy as np

# 랜덤시드 고정시키기
np.random.seed(3)

from keras.preprocessing.image import ImageDataGenerator

# 데이터셋 불러오기
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        'handwriting_shape/train',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'hard_handwriting_shape/test',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D

# 모델 구성하기
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

# 모델 엮기
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# 모델 학습시키기
model.fit_generator(
        train_generator,
        steps_per_epoch=15,
        epochs=200,
        validation_data=test_generator,
        validation_steps=5)

# 모델 평가하기
print("-- Evaluate --")

scores = model.evaluate_generator(
            test_generator,
            steps = 5)

print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

# 모델 예측하기
print("-- Predict --")

output = model.predict_generator(
            test_generator,
            steps = 5)

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

print(output)

# 결과 (원래는 40% 수준)
# -- Evaluate --
# accuracy: 40.00%


Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.
Epoch 1/200


C:\Users\TJ\AppData\Local\Temp\ipykernel_11220\871639182.py:46: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  model.fit_generator(


15/15 [==============================] - 1s 28ms/step - loss: 1.0027 - accuracy: 0.5778 - val_loss: 1.2317 - val_accuracy: 0.3333
Epoch 2/200
15/15 [==============================] - 0s 16ms/step - loss: 0.1482 - accuracy: 1.0000 - val_loss: 2.7925 - val_accuracy: 0.3333
Epoch 3/200
15/15 [==============================] - 0s 15ms/step - loss: 0.0073 - accuracy: 1.0000 - val_loss: 3.2055 - val_accuracy: 0.4000
Epoch 4/200
15/15 [==============================] - 0s 16ms/step - loss: 0.0174 - accuracy: 1.0000 - val_loss: 3.8725 - val_accuracy: 0.4000
Epoch 5/200
15/15 [==============================] - 0s 16ms/step - loss: 0.0014 - accuracy: 1.0000 - val_loss: 3.8739 - val_accuracy: 0.4000
Epoch 6/200
15/15 [==============================] - 0s 16ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 4.1868 - val_accuracy: 0.4000
Epoch 7/200
15/15 [==============================] - 0s 16ms/step - loss: 2.8271e-04 - accuracy: 1.0000 - val_loss: 4.5053 - val_accuracy: 0.4000
Epoch 8/200
15

15/15 [==============================] - 0s 16ms/step - loss: 2.1987e-06 - accuracy: 1.0000 - val_loss: 5.8280 - val_accuracy: 0.4000
Epoch 58/200
15/15 [==============================] - 0s 15ms/step - loss: 2.1564e-06 - accuracy: 1.0000 - val_loss: 5.8384 - val_accuracy: 0.4000
Epoch 59/200
15/15 [==============================] - 0s 15ms/step - loss: 2.0848e-06 - accuracy: 1.0000 - val_loss: 5.8412 - val_accuracy: 0.4000
Epoch 60/200
15/15 [==============================] - 0s 15ms/step - loss: 2.0160e-06 - accuracy: 1.0000 - val_loss: 5.8552 - val_accuracy: 0.4000
Epoch 61/200
15/15 [==============================] - 0s 16ms/step - loss: 1.9656e-06 - accuracy: 1.0000 - val_loss: 5.8730 - val_accuracy: 0.4000
Epoch 62/200
15/15 [==============================] - 0s 15ms/step - loss: 1.9073e-06 - accuracy: 1.0000 - val_loss: 5.8829 - val_accuracy: 0.4000
Epoch 63/200
15/15 [==============================] - 0s 16ms/step - loss: 1.8650e-06 - accuracy: 1.0000 - val_loss: 5.8793 - val_a

Epoch 113/200
15/15 [==============================] - 0s 16ms/step - loss: 5.3512e-07 - accuracy: 1.0000 - val_loss: 6.2717 - val_accuracy: 0.4000
Epoch 114/200
15/15 [==============================] - 0s 16ms/step - loss: 5.2187e-07 - accuracy: 1.0000 - val_loss: 6.2786 - val_accuracy: 0.4000
Epoch 115/200
15/15 [==============================] - 0s 16ms/step - loss: 5.1392e-07 - accuracy: 1.0000 - val_loss: 6.2859 - val_accuracy: 0.4000
Epoch 116/200
15/15 [==============================] - 0s 16ms/step - loss: 5.0333e-07 - accuracy: 1.0000 - val_loss: 6.2912 - val_accuracy: 0.4000
Epoch 117/200
15/15 [==============================] - 0s 16ms/step - loss: 4.9803e-07 - accuracy: 1.0000 - val_loss: 6.2955 - val_accuracy: 0.4000
Epoch 118/200
15/15 [==============================] - 0s 16ms/step - loss: 4.8743e-07 - accuracy: 1.0000 - val_loss: 6.3038 - val_accuracy: 0.4000
Epoch 119/200
15/15 [==============================] - 0s 16ms/step - loss: 4.7419e-07 - accuracy: 1.0000 - val_

15/15 [==============================] - 0s 17ms/step - loss: 2.0398e-07 - accuracy: 1.0000 - val_loss: 6.5592 - val_accuracy: 0.4000
Epoch 169/200
15/15 [==============================] - 0s 16ms/step - loss: 2.0398e-07 - accuracy: 1.0000 - val_loss: 6.5705 - val_accuracy: 0.4000
Epoch 170/200
15/15 [==============================] - 0s 16ms/step - loss: 1.9073e-07 - accuracy: 1.0000 - val_loss: 6.5727 - val_accuracy: 0.4000
Epoch 171/200
15/15 [==============================] - 0s 16ms/step - loss: 1.8279e-07 - accuracy: 1.0000 - val_loss: 6.5778 - val_accuracy: 0.4000
Epoch 172/200
15/15 [==============================] - 0s 16ms/step - loss: 1.7749e-07 - accuracy: 1.0000 - val_loss: 6.5826 - val_accuracy: 0.4000
Epoch 173/200
15/15 [==============================] - 0s 15ms/step - loss: 1.7484e-07 - accuracy: 1.0000 - val_loss: 6.5937 - val_accuracy: 0.4000
Epoch 174/200
15/15 [==============================] - 0s 16ms/step - loss: 1.7484e-07 - accuracy: 1.0000 - val_loss: 6.5981 -

C:\Users\TJ\AppData\Local\Temp\ipykernel_11220\871639182.py:56: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  scores = model.evaluate_generator(
C:\Users\TJ\AppData\Local\Temp\ipykernel_11220\871639182.py:65: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  output = model.predict_generator(


[[0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.020 0.979]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.001 0.000 0.999]
 [0.000 0.006 0.994]
 [0.000 0.000 1.000]
 [0.900 0.000 0.100]
 [0.747 0.002 0.252]
 [0.043 0.003 0.953]]
